-- ==========================================
-- 📘 DOCUMENTACIÓN DE BASE DE DATOS (FORTNITE STATS PRO)
-- ==========================================

-- 1. TABLA: SNAPSHOTS (Historial de Jugadores)
-- ------------------------------------------
-- Esta tabla guarda "fotos" del rendimiento de un jugador en un momento dado.
-- Nos permite construir gráficas de progreso (ej. cómo mejoró su K/D la última semana).
create table if not exists snapshots (
  id bigint generated by default as identity primary key, -- Identificador único
  player text not null,        -- Nombre del jugador (ej. "Ninja")
  recorded_at timestamp with time zone default timezone('utc'::text, now()) not null, -- Cuándo se guardó
  kd numeric,                  -- Ratio de Bajas/Muertes
  win_rate numeric,            -- Porcentaje de Victorias
  wins integer,                -- Total de Victorias
  matches integer,             -- Total de Partidas jugadas
  level integer                -- Nivel del Pase de Batalla actual
);

-- 2. TABLA: SITE_STATS (Estadísticas del Sitio)
-- ------------------------------------------
-- Un contador simple para saber cuánta gente entra a la web.
-- Solo tiene una fila (ID=1) que se actualiza constantemente.
create table if not exists site_stats (
  id bigint primary key generated always as identity,
  visits bigint default 0      -- Contador de visitas totales
);

-- Inicializar el contador en 0 si no existe
-- Inicializar el contador en 0 si no existe
insert into site_stats (id, visits)
overriding system value
values (1, 0)
on conflict (id) do nothing;

-- 3. TABLA: SEARCH_LOGS (Registro de Búsquedas) [NUEVO]
-- ------------------------------------------
-- Guarda qué jugadores busca la gente. Útil para ver tendencias ("Top Buscados").
create table if not exists search_logs (
  id bigint generated by default as identity primary key,
  query text not null,         -- Qué escribieron (ej. "Tfue")
  searched_at timestamp with time zone default timezone('utc'::text, now()) -- Cuándo
);

-- ==========================================
-- 🔐 SEGURIDAD (RLS - Row Level Security)
-- ==========================================

-- Habilitar seguridad en las tablas
alter table site_stats enable row level security;
alter table snapshots enable row level security;
alter table search_logs enable row level security;

-- POLÍTICAS DE ACCESO (Permitir lectura/escritura pública por ahora)
-- Nota: En producción idealmente restringiríamos la escritura, pero para estas stats públicas está bien.

-- Site Stats: Todos pueden ver y sumar visitas
create policy "Public Access Stats" on site_stats for all using (true);

-- Snapshots: Todos pueden leer el historial y guardar nuevos datos si la API lo pide
create policy "Public Access Snapshots" on snapshots for all using (true);

-- Search Logs: Permitir insertar búsquedas (idealmente solo insert, no lectura pública si es privado)
create policy "Public Insert Logs" on search_logs for insert with check (true);

